CREATE DATABASE IF NOT EXISTS BEAUTY_SALOON DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER 'appUser'@'localhost' IDENTIFIED BY 'IVr69LG8*l';

GRANT SELECT,INSERT,UPDATE,DELETE
ON `beauty_saloon`.*
TO appUser@localhost
IDENTIFIED BY PASSWORD 'IVr69LG8*l';

GRANT SELECT,INSERT,UPDATE,DELETE
ON `beauty_saloon`.*
TO appUser@'%'
IDENTIFIED BY PASSWORD'IVr69LG8*l';